export interface User {
  id: number;
  name: string;
  email: string;
  role: string;
  skill: string;
  status: string;
}

export const users: User[] = [
  {
    id: 1,
    name: 'John Smith',
    email: 'john.smith@example.com',
    role: 'react developer',
    skill: 'javascript',
    status: 'active',
  },
  {
    id: 1,
    name: 'John Smith',
    email: 'john.smith@example.com',
    role: 'react developer',
    skill: 'javascript',
    status: 'pending',
  },
  {
    id: 1,
    name: 'John Smith',
    email: 'john.smith@example.com',
    role: 'react developer',
    skill: 'javascript',
    status: 'active',
  },
  {
    id: 1,
    name: 'John Smith',
    email: 'john.smith@example.com',
    role: 'react developer',
    skill: 'javascript',
    status: 'active',
  },
  {
    id: 1,
    name: 'John Smith',
    email: 'john.smith@example.com',
    role: 'react developer',
    skill: 'javascript',
    status: 'active',
  },
  {
    id: 1,
    name: 'John Smith',
    email: 'john.smith@example.com',
    role: 'react developer',
    skill: 'javascript',
    status: 'active',
  },
  {
    id: 1,
    name: 'John Smith',
    email: 'john.smith@example.com',
    role: 'react developer',
    skill: 'javascript',
    status: 'active',
  },
  {
    id: 1,
    name: 'John Smith',
    email: 'john.smith@example.com',
    role: 'react developer',
    skill: 'javascript',
    status: 'active',
  },
  {
    id: 1,
    name: 'John Smith',
    email: 'john.smith@example.com',
    role: 'react developer',
    skill: 'javascript',
    status: 'active',
  },
  {
    id: 1,
    name: 'John Smith',
    email: 'john.smith@example.com',
    role: 'react developer',
    skill: 'javascript',
    status: 'active',
  },
  {
    id: 1,
    name: 'John Smith',
    email: 'john.smith@example.com',
    role: 'react developer',
    skill: 'javascript',
    status: 'active',
  },
  {
    id: 1,
    name: 'John Smith',
    email: 'john.smith@example.com',
    role: 'react developer',
    skill: 'javascript',
    status: 'active',
  },
  {
    id: 1,
    name: 'John Smith',
    email: 'john.smith@example.com',
    role: 'react developer',
    skill: 'javascript',
    status: 'active',
  },
  {
    id: 1,
    name: 'John Smith',
    email: 'john.smith@example.com',
    role: 'react developer',
    skill: 'javascript',
    status: 'active',
  },
  {
    id: 1,
    name: 'John Smith',
    email: 'john.smith@example.com',
    role: 'react developer',
    skill: 'javascript',
    status: 'active',
  },
  {
    id: 1,
    name: 'John Smith',
    email: 'john.smith@example.com',
    role: 'react developer',
    skill: 'javascript',
    status: 'active',
  },
  {
    id: 1,
    name: 'John Smith',
    email: 'john.smith@example.com',
    role: 'react developer',
    skill: 'javascript',
    status: 'active',
  },
  {
    id: 1,
    name: 'John Smith',
    email: 'john.smith@example.com',
    role: 'react developer',
    skill: 'javascript',
    status: 'active',
  },
  {
    id: 1,
    name: 'John Smith',
    email: 'john.smith@example.com',
    role: 'react developer',
    skill: 'javascript',
    status: 'active',
  },
  {
    id: 1,
    name: 'John Smith',
    email: 'john.smith@example.com',
    role: 'react developer',
    skill: 'javascript',
    status: 'active',
  },
  {
    id: 1,
    name: 'John Smith',
    email: 'john.smith@example.com',
    role: 'react developer',
    skill: 'javascript',
    status: 'active',
  },
  {
    id: 1,
    name: 'John Smith',
    email: 'john.smith@example.com',
    role: 'react developer',
    skill: 'javascript',
    status: 'active',
  },
  {
    id: 1,
    name: 'John Smith',
    email: 'john.smith@example.com',
    role: 'react developer',
    skill: 'javascript',
    status: 'active',
  },
  {
    id: 1,
    name: 'John Smith',
    email: 'john.smith@example.com',
    role: 'react developer',
    skill: 'javascript',
    status: 'active',
  },
  {
    id: 1,
    name: 'John Smith',
    email: 'john.smith@example.com',
    role: 'react developer',
    skill: 'javascript',
    status: 'active',
  },
  {
    id: 1,
    name: 'John Smith',
    email: 'john.smith@example.com',
    role: 'react developer',
    skill: 'javascript',
    status: 'active',
  },
  {
    id: 1,
    name: 'John Smith',
    email: 'john.smith@example.com',
    role: 'react developer',
    skill: 'javascript',
    status: 'active',
  },
  {
    id: 1,
    name: 'John Smith',
    email: 'john.smith@example.com',
    role: 'react developer',
    skill: 'javascript',
    status: 'active',
  },
  {
    id: 1,
    name: 'John Smith',
    email: 'john.smith@example.com',
    role: 'react developer',
    skill: 'javascript',
    status: 'active',
  },
  {
    id: 1,
    name: 'John Smith',
    email: 'john.smith@example.com',
    role: 'react developer',
    skill: 'javascript',
    status: 'active',
  },
  {
    id: 1,
    name: 'John Smith',
    email: 'john.smith@example.com',
    role: 'react developer',
    skill: 'javascript',
    status: 'active',
  },
  {
    id: 1,
    name: 'John Smith',
    email: 'john.smith@example.com',
    role: 'react developer',
    skill: 'javascript',
    status: 'active',
  },
  {
    id: 1,
    name: 'John Smith',
    email: 'john.smith@example.com',
    role: 'react developer',
    skill: 'javascript',
    status: 'active',
  },
  {
    id: 1,
    name: 'John Smith',
    email: 'john.sdfsmith@example.com',
    role: 'react developer',
    skill: 'javascript',
    status: 'active',
  },
  {
    id: 1,
    name: 'John Smith',
    email: 'johnsdf.smith@example.com',
    role: 'react developer',
    skill: 'javascript',
    status: 'active',
  },
];
